# Generated by Django 3.1.7 on 2021-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100)),
                ('title', models.CharField(default=True, max_length=100)),
                ('image', models.ImageField(upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Image')),
                ('facebook', models.CharField(default=True, max_length=100)),
                ('instagram', models.CharField(default=True, max_length=100)),
                ('twitter', models.CharField(default=True, max_length=100)),
                ('linklind', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='portfilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='Image')),
                ('image2', models.ImageField(upload_to='Image')),
                ('image3', models.ImageField(upload_to='Image')),
            ],
        ),
    ]
